[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://holistic-money-backend.herokuapp.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/404"
  to = "/index-override.html"
  status = 200 